apiVersion: v1
kind: Service
metadata:
  name: dotnetapp
  labels:
    name: dotnetapp
spec:
  type: LoadBalancer
  ports:
  - name: http
    port: {{.Values.service.port}}
    targetPort: {{.Values.service.port}}
  selector:
    app: dotnetapp